"""
 start.py

  Created by Julien Zouein on 10/11/2023.
  Copyright © 2023 Sigmedia.tv. All rights reserved.
  Copyright © 2023 Julien Zouein (zoueinj@tcd.ie)
----------------------------------------------------------------------------

Define all the functions needed to process the json files generated by AOM inspection tool.
"""

import cv2
import numpy as np

import json


def read_json_file(json_file):
    """
    Read the json file and return the dictionary containing the data
    :param json_file: json file to read
    :return: dictionary containing the data
    """
    with open(json_file, "r") as file:
        data = json.loads(file.read())
    return data


def get_frame_data(data, frame_number):
    """
    Get the data of a specific frame
    :param data: dictionary containing the data
    :param frame_number: frame number
    :return: dictionary containing the data of the frame
    """
    return data[frame_number]
